<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="0" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-09-24T23:28:01 CDT" name="Default Suite" finished-at="2023-09-24T23:28:10 CDT" duration-ms="8821">
    <groups>
    </groups>
    <test started-at="2023-09-24T23:28:01 CDT" name="seleniumWebdriverFramework" finished-at="2023-09-24T23:28:10 CDT" duration-ms="8821">
      <class name="com.testcases.TestCasesTestNG">
        <test-method signature="testCaseLogin()[pri:1, instance:com.testcases.TestCasesTestNG@1d269ed7]" started-at="2023-09-24T23:28:01 CDT" name="testCaseLogin" description="LOGIN TESTS" finished-at="2023-09-24T23:28:07 CDT" duration-ms="5849" status="FAIL">
          <exception class="java.lang.VerifyError">
            <message>
              <![CDATA[Expecting a stackmap frame at branch target 57
Exception Details:
  Location:
    com/library/BrowserFunctions.launchApplication()V @9: invokestatic
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0000000: b200 4e2a 2ab8 0054 4cb8 005a 2bb6 005e
    0000010: 2ab4 0011 b900 1501 00b9 001b 0100 b900
    0000020: 2101 002a b400 112a b400 0bb9 0026 0200
    0000030: 1400 2ab8 002c a700 0d4d b800 5a2c b600
    0000040: 622c bfb8 005a b600 65b1               
  Exception Handler Table:
    bci [9, 57] => handler: 57
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.VerifyError: Expecting a stackmap frame at branch target 57
Exception Details:
  Location:
    com/library/BrowserFunctions.launchApplication()V @9: invokestatic
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0000000: b200 4e2a 2ab8 0054 4cb8 005a 2bb6 005e
    0000010: 2ab4 0011 b900 1501 00b9 001b 0100 b900
    0000020: 2101 002a b400 112a b400 0bb9 0026 0200
    0000030: 1400 2ab8 002c a700 0d4d b800 5a2c b600
    0000040: 622c bfb8 005a b600 65b1               
  Exception Handler Table:
    bci [9, 57] => handler: 57

at com.testcases.TestCasesTestNG.testCaseLogin(TestCasesTestNG.java:18)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.VerifyError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseLogin -->
        <test-method signature="testCaseLoginReset()[pri:2, instance:com.testcases.TestCasesTestNG@1d269ed7]" started-at="2023-09-24T23:28:07 CDT" name="testCaseLoginReset" description="LOGIN TESTS" finished-at="2023-09-24T23:28:08 CDT" duration-ms="1224" status="FAIL">
          <exception class="java.lang.VerifyError">
            <message>
              <![CDATA[Expecting a stackmap frame at branch target 57
Exception Details:
  Location:
    com/library/BrowserFunctions.launchApplication()V @9: invokestatic
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0000000: b200 4e2a 2ab8 0054 4cb8 005a 2bb6 005e
    0000010: 2ab4 0011 b900 1501 00b9 001b 0100 b900
    0000020: 2101 002a b400 112a b400 0bb9 0026 0200
    0000030: 1400 2ab8 002c a700 0d4d b800 5a2c b600
    0000040: 622c bfb8 005a b600 65b1               
  Exception Handler Table:
    bci [9, 57] => handler: 57
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.VerifyError: Expecting a stackmap frame at branch target 57
Exception Details:
  Location:
    com/library/BrowserFunctions.launchApplication()V @9: invokestatic
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0000000: b200 4e2a 2ab8 0054 4cb8 005a 2bb6 005e
    0000010: 2ab4 0011 b900 1501 00b9 001b 0100 b900
    0000020: 2101 002a b400 112a b400 0bb9 0026 0200
    0000030: 1400 2ab8 002c a700 0d4d b800 5a2c b600
    0000040: 622c bfb8 005a b600 65b1               
  Exception Handler Table:
    bci [9, 57] => handler: 57

at com.testcases.TestCasesTestNG.testCaseLoginReset(TestCasesTestNG.java:34)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.VerifyError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseLoginReset -->
        <test-method signature="testCaseWelcome()[pri:3, instance:com.testcases.TestCasesTestNG@1d269ed7]" started-at="2023-09-24T23:28:08 CDT" name="testCaseWelcome" description="LOGIN TESTS" finished-at="2023-09-24T23:28:09 CDT" duration-ms="1440" status="FAIL">
          <exception class="java.lang.VerifyError">
            <message>
              <![CDATA[Expecting a stackmap frame at branch target 57
Exception Details:
  Location:
    com/library/BrowserFunctions.launchApplication()V @9: invokestatic
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0000000: b200 4e2a 2ab8 0054 4cb8 005a 2bb6 005e
    0000010: 2ab4 0011 b900 1501 00b9 001b 0100 b900
    0000020: 2101 002a b400 112a b400 0bb9 0026 0200
    0000030: 1400 2ab8 002c a700 0d4d b800 5a2c b600
    0000040: 622c bfb8 005a b600 65b1               
  Exception Handler Table:
    bci [9, 57] => handler: 57
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.VerifyError: Expecting a stackmap frame at branch target 57
Exception Details:
  Location:
    com/library/BrowserFunctions.launchApplication()V @9: invokestatic
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0000000: b200 4e2a 2ab8 0054 4cb8 005a 2bb6 005e
    0000010: 2ab4 0011 b900 1501 00b9 001b 0100 b900
    0000020: 2101 002a b400 112a b400 0bb9 0026 0200
    0000030: 1400 2ab8 002c a700 0d4d b800 5a2c b600
    0000040: 622c bfb8 005a b600 65b1               
  Exception Handler Table:
    bci [9, 57] => handler: 57

at com.testcases.TestCasesTestNG.testCaseWelcome(TestCasesTestNG.java:47)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.VerifyError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseWelcome -->
      </class> <!-- com.testcases.TestCasesTestNG -->
    </test> <!-- seleniumWebdriverFramework -->
  </suite> <!-- Default Suite -->
</testng-results>
